//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Date
    {
        public int ID { get; set; }
        public System.DateTime DATE1 { get; set; }
        public string Login { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
