//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public string Section { get; set; }
        public string Article { get; set; }
        public int Id { get; set; }
        public string Link { get; set; }
    }
}
